services:
  - type: web
    name: nandana-inventory
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_VERSION
        value: 18.20.0
